version: '3.9'
services:
  db:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"