spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: postgres_user
    password: postgres_password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true