spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: postgres_user
    password: postgres_password
    jpa:
      hibernate:
        ddl-auto: create
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      #generate-ddl: true